export enum Opcode {
  CMSG_AUTH,
  SMSG_AUTH_SUCCESS,
  CMSG_UPDATE_RATE,
  CMSG_PING,
  SMSG_PONG,
  MSG_JOIN,
  CMSG_MOVE,
  SMSG_ENV_INIT,
  SMSG_ENV_UPDATE,
  SMSG_OBJECT,
  SMGS_OBJECT_DESTROY,
  SMSG_UPDATE,
  SMSG_DESTROY,
  CMSG_LEAVE
}
