import {TILE_SIZE} from "@leela/common";

const SERVER_HOST = "http://localhost:3000";

const INTERPOLATE = true;
const INTERPOLATE_BUFFER_MS = 1000;
const INTERPOLATE_DROP_DUPLICATES = true;
const INTERPOLATE_DROP_DUPLICATES_MAX = 3;

const ENTITY_EXTRAPOLATE = true;
const ENTITY_EXTRAPOLATE_MAX_MS = 250;
const ENTITY_EXTRAPOLATE_PAST = true;

const CLIENT_PREDICT = true;
const CLIENT_SMOOTH = true;
const CLIENT_SMOOTH_POS_ERROR_PRECISION = 0.1;
const CLIENT_SMOOTH_POS_ERROR_THRESHOLD = TILE_SIZE;
const CLIENT_SMOOTH_POSITION_MS = 100;

const CLIENT_CMD_LOOP = false;
const CLIENT_CMD_RATE = -1;

const CLIENT_UPDATE_RATE = -1;

const PING_DELAY_MS = 1000;

const TIMESYNC_INTERVAL_MS = 30000;

const DEBUG_MODE = true;

export {
    SERVER_HOST,
    INTERPOLATE,
    INTERPOLATE_BUFFER_MS,
    INTERPOLATE_DROP_DUPLICATES,
    INTERPOLATE_DROP_DUPLICATES_MAX,
    ENTITY_EXTRAPOLATE,
    ENTITY_EXTRAPOLATE_MAX_MS,
    ENTITY_EXTRAPOLATE_PAST,
    CLIENT_PREDICT,
    CLIENT_SMOOTH_POS_ERROR_PRECISION,
    CLIENT_SMOOTH_POS_ERROR_THRESHOLD,
    CLIENT_SMOOTH,
    CLIENT_SMOOTH_POSITION_MS,
    CLIENT_CMD_LOOP,
    CLIENT_CMD_RATE,
    CLIENT_UPDATE_RATE,
    PING_DELAY_MS,
    TIMESYNC_INTERVAL_MS,
    DEBUG_MODE
};
