const SERVER_HOST = "http://localhost:3000/";

const ENTITY_EXTRAPOLATE = true;
const ENTITY_EXTRAPOLATE_MAX_MS = 250;

const CLIENT_PREDICT = true;
const CLIENT_SMOOTH = true;
const CLIENT_SMOOTH_MS = 100;

const CLIENT_CMD_RATE = -1;
const CLIENT_UPDATE_RATE = -1;

export {
    SERVER_HOST,
    ENTITY_EXTRAPOLATE,
    ENTITY_EXTRAPOLATE_MAX_MS,
    CLIENT_PREDICT,
    CLIENT_SMOOTH,
    CLIENT_SMOOTH_MS,
    CLIENT_CMD_RATE,
    CLIENT_UPDATE_RATE
};
