const SERVER_HOST = "http://localhost:3000/";

const INTERPOLATE = true;
const INTERPOLATE_BUFFER_MS = 1000;
const INTERPOLATE_DUPLICATES = false;

const ENTITY_EXTRAPOLATE = true;
const ENTITY_EXTRAPOLATE_MAX_MS = 250;
const ENTITY_EXTRAPOLATE_PAST = true;

const CLIENT_PREDICT = true;
const CLIENT_SHOW_ERROR = false;
const CLIENT_SMOOTH = true;
const CLIENT_SMOOTH_PRECISION = 0.1;
const CLIENT_SMOOTH_SNAP_RATIO = 0.1;
const CLIENT_SMOOTH_MAX_MS = 10000;
const CLIENT_SMOOTH_FUNCTION = (x: number): number => 1 - Math.pow(1 - x, 5);

const CLIENT_CMD_RATE = -1;
const CLIENT_UPDATE_RATE = -1;

export {
    SERVER_HOST,
    INTERPOLATE,
    INTERPOLATE_BUFFER_MS,
    INTERPOLATE_DUPLICATES,
    ENTITY_EXTRAPOLATE,
    ENTITY_EXTRAPOLATE_MAX_MS,
    ENTITY_EXTRAPOLATE_PAST,
    CLIENT_PREDICT,
    CLIENT_SMOOTH_PRECISION,
    CLIENT_SMOOTH_SNAP_RATIO,
    CLIENT_SMOOTH,
    CLIENT_SMOOTH_MAX_MS,
    CLIENT_SMOOTH_FUNCTION,
    CLIENT_CMD_RATE,
    CLIENT_UPDATE_RATE
};
