const INTERPOLATE_MS = 200;

const SIMULATION_RATE = 20;
const SNAPSHOT_RATE = -1;

const FRACTION_DIGITS = 1;

export {
    INTERPOLATE_MS,
    SIMULATION_RATE,
    SNAPSHOT_RATE,
    FRACTION_DIGITS
};
