const INTERPOLATE_MS = 200;

const SIMULATION_RATE = 20;
const SIMULATION_DELTA_MS = 1000 / SIMULATION_RATE;
const SNAPSHOT_RATE = -1;

const FRACTION_DIGITS = 1;

export {
    INTERPOLATE_MS,
    SIMULATION_RATE,
    SIMULATION_DELTA_MS,
    SNAPSHOT_RATE,
    FRACTION_DIGITS
};
