const TILE_SIZE = 32;

const TILES_WIDTH = 20;
const TILES_HEIGHT = 20;

const WORLD_WIDTH = TILE_SIZE * TILES_WIDTH;
const WORLD_HEIGHT = TILE_SIZE * TILES_HEIGHT;

const CHAR_SKINS = 6;
const CHAR_SPEED = 120;
const CHAR_SIZE = TILE_SIZE;

export {
    TILE_SIZE,
    TILES_WIDTH,
    TILES_HEIGHT,
    WORLD_WIDTH,
    WORLD_HEIGHT,
    CHAR_SKINS,
    CHAR_SPEED,
    CHAR_SIZE
}
