const TILE_SIZE = 32;

const UNIT_BODY_WIDTH = TILE_SIZE / 2;
const UNIT_BODY_HEIGHT = TILE_SIZE;

const UNIT_SKINS = 7;
const UNIT_WALK_SPEED = 100;
const UNIT_RUN_SPEED = 200;

const INVENTORY_SIZE = 3;

export {
    TILE_SIZE,
    UNIT_BODY_WIDTH,
    UNIT_BODY_HEIGHT,
    UNIT_SKINS,
    UNIT_WALK_SPEED,
    UNIT_RUN_SPEED,
    INVENTORY_SIZE
}
