const WORLD_WIDTH = 1300;
const WORLD_HEIGHT = 1300;

const CHAR_SKINS = 6;
const CHAR_SPEED = 120;
const CHAR_SIZE = 32;

export {
    WORLD_WIDTH,
    WORLD_HEIGHT,
    CHAR_SKINS,
    CHAR_SPEED,
    CHAR_SIZE
}
