const INTERPOLATE_MS = 250;

const SIMULATION_RATE = 20;
const SIMULATION_DELTA = 1 / SIMULATION_RATE;
const SIMULATION_DELTA_MS = SIMULATION_DELTA * 1000;

const FRACTION_DIGITS = 1;

export {
    INTERPOLATE_MS,
    SIMULATION_RATE,
    SIMULATION_DELTA,
    SIMULATION_DELTA_MS,
    FRACTION_DIGITS
};
